name: “Terraform-Plan-Infra-Plan"

on:
push:
branches:
- FeatureBranch-l

name: “Terraform”

runs-on: ubuntu-latest

env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
AWs_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_KEY }}
AUS_REGION: ap-south-1

steps:
- name: Checkout
uses: actions/checkout@v2
- name: Setup Terraform
uses: hashicorp/setup-terraforngvi

- name: Terraform Init
1d: init

run: terraform init

- name: Terraform Plan
  id: plan

  run: terraform plan